version: '3'
services:
  backend:
    build:
      context: ./backend
      # target: development 
    volumes:
      - ./backend:/app/
      - /app/node_modules
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    env_file:
      - ./backend/.env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
