version: "3"
services:
  backend:
    container_name: ft_transcendence_backend
    build:
      context: ./backend
      # target: development
    volumes:
      - ./backend:/app/
      - backend_node_module:/app/node_modules
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    environment:
      POSTGRES_HOST: ft_transcendence_postgres

  frontend:
    container_name: ft_transcendence_frontend
    # Specify the directory where dockerfile is located.
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app/
      - frontend_node_module:/app/node_modules
    ports:
      - "8080:8080"
    # Link to containers in another service and also express dependency between services in the same way as depends_on.
    links:
      - backend

  postgres:
    container_name: ft_transcendence_postgres
    image: postgres:13
    env_file:
      - ./backend/.env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    links:
      - postgres:postgres
    container_name: ft_transcendence_pgadmin
    image: dpage/pgadmin4
    ports:
      - "8081:80"
    volumes:
      - pgadmin:/var/lib/pgadmin
    env_file:
      - ./backend/.env
    depends_on:
      - postgres

volumes:
  backend_node_module:
  frontend_node_module:
  pgdata:
  pgadmin:
