version: '3'
services:
  backend:
    container_name: backend
    build:
      context: ./backend
      # target: development
    volumes:
      - ./backend:/usr/src/app/
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    command: npm run start:dev
    env_file:
      - ./backend/.env
    networks:
      - api
    depends_on:
      - postgres
  postgres:
    image: postgres:13
    container_name: postgres
    networks:
      - api
    env_file:
      - ./backend/.env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

networks:
 api:

volumes:
 pgdata: