version: '3'
services:
  backend:
    container_name: ft_transcendence_backend
    build:
      context: ./backend
      # target: development 
    volumes:
      - ./backend:/app/
      - node_module:/app/node_modules
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    depends_on:
      - postgres

  postgres:
    container_name: ft_transcendence_postgres
    image: postgres:13
    env_file:
      - ./backend/.env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  pgadmin:
    links:
      - postgres:postgres
    container_name: ft_transcendence_pgadmin
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    volumes:
      - pgadmin:/var/lib/pgadmin
    env_file:
      - ./backend/.env

volumes:
  pgdata:
  pgadmin:
  node_module:
